plugins {
    id 'java'
    id 'application'
}

group = 'com.example'
version = '1.0.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenLocal()
    mavenCentral()
}

ext {
    pispiQrcodeVersion = '0.1.2'
}

dependencies {
    implementation "int.bceao.pispi:qrcode:${pispiQrcodeVersion}"
}

application {
    mainClass = 'com.example.Main'
}
